"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================
# Helper function for env variables
# =============================
def get_env_variable(var_name, default=None, cast=str):
    """
    Get an environment variable or return default.
    Supports casting (str, int, bool, etc.)
    """
    value = os.getenv(var_name, default)
    if value is None:
        raise Exception(f"Missing required environment variable: {var_name}")
    try:
        return cast(value)
    except Exception as e:
        raise ValueError(f"Error casting environment variable {var_name}: {e}")



REDIS_HOST = get_env_variable("REDIS_HOST", "127.0.0.1")
REDIS_PORT = get_env_variable("REDIS_PORT", 6379, cast=int)
REDIS_URL = get_env_variable("REDIS_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
BASE_URL = get_env_variable("BASE_URL", "http://localhost:8000/api/v1")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
load_dotenv(BASE_DIR.parent / ".env")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6j))8vb%nflvwwb3-n4pp5k^==r6@8oy4*ruxtqmmqj3aj4ea7'
DEBUG = get_env_variable("DEBUG", "True") == "True"
ALLOWED_HOSTS = ['0.0.0.0', 'nginx', 'localhost', '127.0.0.1']
ROOT_URLCONF = 'backend.urls'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTH_USER_MODEL = 'accounts.User'   
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3030'
]
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3030'
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG 

# =============================
MTN_MOMO_CONFIG = {
    'BASE_URL': 'https://sandbox.momodeveloper.mtn.com',
    'PRIMARY_KEY': 'efc825a16cd54e91b257495f3798fc73',
    'SECONDARY_KEY': '82ab603816854e039508b274aec3dca4',
    'CALLBACK_HOST': 'http://localhost:3030',
    'ENVIRONMENT': 'sandbox',  
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'loan',
    'transactions',
    'meter',
    'rest_framework',
    'cities_light',
    'drf_yasg',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# =============================
# Base URL
# =============================
# Used by get_base_url() to construct links in emails
DEFAULT_HTTP_PROTOCOL = get_env_variable("DEFAULT_HTTP_PROTOCOL", "http")
DOMAIN_NAME = get_env_variable("DOMAIN_NAME", "localhost:3000")
BASE_URL = get_env_variable("BASE_URL", "http://localhost:8000/api/v1")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'project',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": 60,  
        'OPTIONS': {
            'options': '-c search_path=custom,public'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# =============================
# Email
# =============================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = get_env_variable("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = get_env_variable("EMAIL_PORT", 587, cast=int)
EMAIL_USE_TLS = get_env_variable("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = get_env_variable("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = get_env_variable("EMAIL_HOST_USER", "kawumalatiif5@gmail.com")
EMAIL_HOST_PASSWORD = get_env_variable("EMAIL_HOST_PASSWORD", "onlvknccibgjoaly")
DEFAULT_FROM_EMAIL = get_env_variable("DEFAULT_EMAIL_SENDER", EMAIL_HOST_USER)
DEFAULT_EMAIL_SENDER = DEFAULT_FROM_EMAIL

# =============================
# Celery & Redis
# =============================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'

CELERY_BROKER_URL = get_env_variable("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = get_env_variable("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_TIMEZONE = get_env_variable("CELERY_TIMEZONE", "Africa/Nairobi")
# Run tasks eagerly in local dev to avoid needing Redis/Celery worker
CELERY_TASK_ALWAYS_EAGER = get_env_variable("CELERY_TASK_ALWAYS_EAGER", "True") == "True"

# JWT settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
from datetime import timedelta
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_COOKIE': 'AUTHENTICATION_COOKIE', 
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SECURE': False, 
    'AUTH_COOKIE_SAMESITE': 'Lax',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}