# Generated by Django 5.2 on 2026-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_admin', '0004_rename_portal_admi_compone_idx_portal_admi_compone_bb8dbe_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('User Edit', 'User Edit'), ('User Delete', 'User Delete'), ('Account Suspension', 'Account Suspension'), ('Account Reactivation', 'Account Reactivation'), ('Credential Reset', 'Credential Reset'), ('KYC Verify', 'KYC Verify'), ('KYC Reject', 'KYC Reject'), ('Meter Register', 'Meter Register'), ('Meter Deactivate', 'Meter Deactivate'), ('Meter Delete', 'Meter Delete'), ('Meter Transfer', 'Meter Transfer'), ('Refund', 'Refund'), ('Penalty Waiver', 'Penalty Waiver'), ('Credit Limit Override', 'Credit Limit Override'), ('Transaction Reverse', 'Transaction Reverse'), ('Fraud Flag', 'Fraud Flag'), ('Fraud Clear', 'Fraud Clear'), ('Staff Create', 'Staff Create'), ('Staff Deactivate', 'Staff Deactivate'), ('Settings Change', 'Settings Change'), ('Token Redelivery', 'Token Redelivery'), ('Loan Approve', 'Loan Approve'), ('Loan Reject', 'Loan Reject')], db_index=True, max_length=30),
        ),
    ]
