from django.urls import path
from .views import (
    AdminDashboardView,
    UserManagementView,
    MeterManagementView,
    ToggleUserStatusView,
    UserDetailView,
    AdminStatsView,
    LoanManagementView,
    AdminAccountView,
    AdminPasswordChangeView,
    AdminNotificationSettingsView,
    AdminSessionManagementView,
    AdminActivityLogView,
    LoanTiersView,
    LoanTierDetailView,
    TariffsView,
    TariffDetailView,
    LoanDetailView,
)

urlpatterns = [
    path('dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('users/', UserManagementView.as_view(), name='admin-users'),
    path('users/<int:user_id>/', UserDetailView.as_view(), name='user-detail'),
    path('meters/', MeterManagementView.as_view(), name='admin-meters'),
    path('stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('toggle-user-status/', ToggleUserStatusView.as_view(), name='toggle-user-status'),
    path('loans/', LoanManagementView.as_view(), name='admin-loans'),
    path('loans/<int:loan_id>/', LoanDetailView.as_view(), name='admin-loan-detail'),
    path('account/', AdminAccountView.as_view(), name='admin-account'),
    path('account/password-change/', AdminPasswordChangeView.as_view(), name='admin-password-change'),
    path('account/notifications/', AdminNotificationSettingsView.as_view(), name='admin-notifications'),
    path('account/sessions/', AdminSessionManagementView.as_view(), name='admin-sessions'),
    path('account/activities/', AdminActivityLogView.as_view(), name='admin-activities'),
    path('loan-tiers/', LoanTiersView.as_view(), name='admin-loan-tiers'),
    path('loan-tiers/<int:pk>/', LoanTierDetailView.as_view(), name='admin-loan-tier-detail'),
    path('tariffs/', TariffsView.as_view(), name='admin-tariffs'),
    path('tariffs/<int:pk>/', TariffDetailView.as_view(), name='admin-tariff-detail'),
]